steps:
  # Step 1:
  - name: 'gcr.io/cloud-builders/mvn'
    entrypoint: bash
    args: ['./scripts/build.bash']
    volumes:
      - name: 'jar'
        path: /jar
  # Step 2:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args: ['./scripts/deploy.bash']
    env:
      - 'PROJECT_ID=$PROJECT_ID'
    volumes:
      - name: 'jar'
        path: /jar
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'build-dataflow-template'
    entrypoint: 'gcloud'
    args: [ 'dataflow', 'flex-template', 'build', 'gs://pharamacy-deda/template/run_template.json', '--image', 'gcr.io/$PROJECT_ID/pharamacy-deda:latest', '--sdk-language', 'JAVA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args: [ './scripts/run_dataflow_job.bash' ]
    env:
        - 'PROJECT_ID=$PROJECT_ID'
        - 'LOCATION=$LOCATION'
        - 'JOB_NAME=testjob'
