name: Build and Deploy to Cloud Run

on:
    push:
        branches:
            - develop

# Environment variables available to all jobs and steps in this workflow
env:
    PROJECT_ID: ${{ secrets.PROJECT_ID }}
    RUN_REGION: us-east4
    SERVICE_NAME: pharamacy-deda-github

jobs:
    setup-build-deploy:
        name: Setup, Build, and Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: mvn package -DskipTests
            - name: Upload Artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: Pharamacy-Data.jar
                  path: target/
    build-docker-image:
        name: build-docker
        needs: setup-build-deploy
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: Retrieve saved jar
              uses: actions/download-artifact@v2
              with:
                  name: Pharamacy-Data.jar
                  path: target/
            - id: 'auth'
              uses: 'google-github-actions/auth@v1'
              with:
                credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

            - name: 'Set up Cloud SDK'
              uses: 'google-github-actions/setup-gcloud@v1'

            - name: 'Use gcloud CLI'
              run: |
                    gcloud auth configure-docker
          # Build the Docker image
            - name: Build
              run: |
                docker build -t gcr.io/$PROJECT_ID/pharamacy-deda-github:latest -f Dockerfile .

      # Push the Docker image to Google Container Registry
            - name: Publish
              run: |
                docker push gcr.io/$PROJECT_ID/pharamacy-deda-github:latest
                  # Push the Docker image to Google Container Registry
            - name: Build Flex Template
              run: |
                gcloud dataflow flex-template build gs://pharamacy-deda/template/run_template_new.json --image gcr.io/$PROJECT_ID/pharamacy-deda-github:latest --sdk-language JAVA

